package frc.robot;

import static edu.wpi.first.units.Units.*;

import java.util.function.Function;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.CANcoderConfiguration;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.Pigeon2Configuration;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.signals.MotorAlignmentValue;
import com.ctre.phoenix6.signals.StaticFeedforwardSignValue;
import com.ctre.phoenix6.sim.ChassisReference;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.ClosedLoopOutputType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.DriveMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerFeedbackType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveModuleConstantsFactory;
import com.pathplanner.lib.path.PathConstraints;

import edu.wpi.first.math.geometry.Rectangle2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Rotation3d;
import edu.wpi.first.math.geometry.Transform3d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.apriltag.AprilTagFieldLayout;
import edu.wpi.first.apriltag.AprilTagFields;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.units.measure.*;
import frc.robot.simulation.BallConstants;

public class Constants 
{
   
    public static final double MAX_VOLTAGE = 12.0; // volts
    
    public static final double ROBOT_HEIGHT = 0.89535; // y direction when bot is faced in the positive x direction; that is, parallel to the intake face
    public static final double ROBOT_WIDTH = 0.84455;

    public static final Pose2d ZEROING_POSE = new Pose2d(3.581, 4.20288, new Rotation2d(Degrees.of(180)));

    public static final double TRANSLATION_SLOW_MULTIPLIER = 0.35;
    public static final double ROTATION_SLOW_MULTIPLIER = 0.5;

    public static final CANBus CAN_CHAIN = new CANBus("rio");

    public static final CANBus CAN_SUPERSTRUCTURE = new CANBus("Superstructure");

    public static final double G = 9.81;

    public class Vision 
    {
        public static final String CAMERA_1_NAME = "limelight";
        public static final Transform3d ROBOT_TO_CAMERA_1 = new Transform3d(
                new Translation3d(Units.inchesToMeters(-10.5238), Units.inchesToMeters(-9.5396), Units.inchesToMeters(9.2734)),
                 new Rotation3d(Units.degreesToRadians(0), Units.degreesToRadians(22.7732), Units.degreesToRadians(90.0 + 37.8094))); // 31.0351)));

        
        public static final String CAMERA_2_NAME = "limelight-right";
        public static final Transform3d ROBOT_TO_CAMERA_2 = new Transform3d(
                new Translation3d(Units.inchesToMeters(-11.743), Units.inchesToMeters(10.009), Units.inchesToMeters(9.0552)),
                new Rotation3d(Units.degreesToRadians(1.615693), Units.degreesToRadians(12.567), Units.degreesToRadians(180.0 + 7.383715))); // TODO bc this is copied from 2025 code

        public static final double ODOMETRY_UPDATE_FREQUENCY = 100.0; // 100.0 Hz for CAN 2.0, which the Roborio runs on
        public static final Matrix<N3, N1> TAG_STANDARD_DEVIATIONS = VecBuilder.fill(0.25, 0.25, 99999);
        public static final Matrix<N3, N1> STATE_STANDARD_DEVIATIONS = VecBuilder.fill(0.05, 0.05, 0.1);
        public static final double MAX_AMBIGUITY = 0.3;

        public static final double MAX_DISTANCE = 3.0;

        // The layout of the AprilTags on the field
        public static final AprilTagFieldLayout TAG_LAYOUT = AprilTagFieldLayout
                .loadField(AprilTagFields.kDefaultField);

        public static final PathConstraints CONSTRAINTS = new PathConstraints(
        6.0, 3.15,
            Units.degreesToRadians(360), Units.degreesToRadians(540));

    }

    public class AlignConstants
    {
        public static final Translation2d HUB = new Translation2d(4.611624, 4.021328);

        public static final Pose2d CLIMB_LEFT = new Pose2d(1.0556, 3.7455 + 0.89535, new Rotation2d(Degrees.of(-90))); //left from driver station
        public static final Pose2d CLIMB_RIGHT = new Pose2d(1.0556, 3.7455 - 0.89535, new Rotation2d(Degrees.of(90))); 
    }
    
    // Generated by the 2026 Tuner X Swerve Project Generator
    // https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
    public class Swerve 
    {
        public static final double AUTOALIGN_STEER_KP = 13.0;// 12.0;
        public static final double AUTOALIGN_STEER_KI = 0.0;
        public static final double AUTOALIGN_STEER_KD = 0.0;
        
        public static final double AUTOALIGN_DRIVE_KP = 6.0;
        public static final double AUTOALIGN_DRIVE_KI = 0.0;
        public static final double AUTOALIGN_DRIVE_KD = 0.0;

        // Both sets of gains need to be tuned to your individual robot.

        // The steer motor uses any SwerveModule.SteerRequestType control request with
        // the
        // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
        public static final Slot0Configs STEER_GAINS = new Slot0Configs()
                .withKP(20.823).withKI(0).withKD(0.49617)
                .withKS(0.0/*0.27579*/).withKV(2.4256).withKA(0.055487)
                .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
        // When using closed-loop control, the drive motor uses the control
        // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
        public static final Slot0Configs DRIVE_GAINS = new Slot0Configs()
                .withKP(0.1).withKI(0).withKD(0)
                .withKS(0.11411/*0*/).withKV(0.1150/*0.124*/);
 
        // The closed-loop output type to use for the steer motors;
        // This affects the PID/FF gains for the steer motors
        public static final ClosedLoopOutputType STEER_CLOSED_LOOP_OUTPUT = ClosedLoopOutputType.Voltage;
        // The closed-loop output type to use for the drive motors;
        // This affects the PID/FF gains for the drive motors
        public static final ClosedLoopOutputType DRIVE_CLOSED_LOOP_OUTPUT = ClosedLoopOutputType.Voltage;

        // The type of motor used for the drive motor
        public static final DriveMotorArrangement DRIVE_MOTOR_TYPE = DriveMotorArrangement.TalonFX_Integrated;
        // The type of motor used for the drive motor
        public static final SteerMotorArrangement STEER_MOTOR_TYPE = SteerMotorArrangement.TalonFX_Integrated;

        // The remote sensor feedback type to use for the steer motors;
        // When not Pro-licensed, Fused*/Sync* automatically fall back to Remote*
        public static final SteerFeedbackType STEER_FEEDBACK_TYPE = SteerFeedbackType.FusedCANcoder;

        // The stator current at which the wheels start to slip;
        // This needs to be tuned to your individual robot
        public static final Current SLIP_CURRENT = Amps.of(120);

        // Initial configs for the drive and steer motors and the azimuth encoder; these
        // cannot be null.
        // Some configs will be overwritten; check the `with*InitialConfigs()` API
        // documentation.
        public static final TalonFXConfiguration DRIVE_INITIAL_CONFIGS = new TalonFXConfiguration();
        public static final TalonFXConfiguration STEER_INITIAL_CONFIGS = new TalonFXConfiguration()
                .withCurrentLimits(
                        new CurrentLimitsConfigs()
                                // Swerve azimuth does not require much torque output, so we can set a
                                // relatively low
                                // stator current limit to help avoid brownouts without impacting performance.
                                .withStatorCurrentLimit(Amps.of(60))
                                .withStatorCurrentLimitEnable(true));
        public static final CANcoderConfiguration ENCODER_INITIAL_CONFIGS = new CANcoderConfiguration();
        // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
        public static final Pigeon2Configuration PIGEON_CONFIGS = null;

        // CAN bus that the devices are located on;
        // All swerve devices must share the same CAN bus
        public static final CANBus SWERVE_CAN_BUS = new CANBus("", "./logs/example.hoot");

        // Theoretical free speed (m/s) at 12 V applied output;
        // This needs to be tuned to your individual robot
        public static final LinearVelocity SPEED_AT_12_VOLTS = MetersPerSecond.of(4.39);

        // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
        // This may need to be tuned to your individual robot
        public static final double COUPLE_RATIO = 4.5;

        public static final double DRIVE_GEAR_RATIO = 7.03125;
        public static final double STEER_GEAR_RATIO = 26.09090909090909;
        public static final Distance WHEEL_RADIUS = Inches.of(2);

        public static final boolean INVERT_LEFT_SIDE = false;
        public static final boolean INVERT_RIGHT_SIDE = true;

        public static final int PIGEON_ID = 2;

        // These are only used for simulation
        public static final MomentOfInertia STEER_INERTIA = KilogramSquareMeters.of(0.01);
        public static final MomentOfInertia DRIVE_INERTIA = KilogramSquareMeters.of(0.01);
        // Simulated voltage necessary to overcome friction
        public static final Voltage STEER_FRICTION_VOLTAGE = Volts.of(0.2);
        public static final Voltage DRIVE_FRICTION_VOLTAGE = Volts.of(0.2);

        public static final SwerveDrivetrainConstants DRIVETRAIN_CONSTANTS = new SwerveDrivetrainConstants()
                .withCANBusName(SWERVE_CAN_BUS.getName())
                .withPigeon2Id(PIGEON_ID)
                .withPigeon2Configs(PIGEON_CONFIGS);

        public static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> CONSTANT_CREATOR = new SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
                .withDriveMotorGearRatio(DRIVE_GEAR_RATIO)
                .withSteerMotorGearRatio(STEER_GEAR_RATIO)
                .withCouplingGearRatio(COUPLE_RATIO)
                .withWheelRadius(WHEEL_RADIUS)
                .withSteerMotorGains(STEER_GAINS)
                .withDriveMotorGains(DRIVE_GAINS)
                .withSteerMotorClosedLoopOutput(STEER_CLOSED_LOOP_OUTPUT)
                .withDriveMotorClosedLoopOutput(DRIVE_CLOSED_LOOP_OUTPUT)
                .withSlipCurrent(SLIP_CURRENT)
                .withSpeedAt12Volts(SPEED_AT_12_VOLTS)
                .withDriveMotorType(DRIVE_MOTOR_TYPE)
                .withSteerMotorType(STEER_MOTOR_TYPE)
                .withFeedbackSource(STEER_FEEDBACK_TYPE)
                .withDriveMotorInitialConfigs(DRIVE_INITIAL_CONFIGS)
                .withSteerMotorInitialConfigs(STEER_INITIAL_CONFIGS)
                .withEncoderInitialConfigs(ENCODER_INITIAL_CONFIGS)
                .withSteerInertia(STEER_INERTIA)
                .withDriveInertia(DRIVE_INERTIA)
                .withSteerFrictionVoltage(STEER_FRICTION_VOLTAGE)
                .withDriveFrictionVoltage(DRIVE_FRICTION_VOLTAGE);

        // Front Left
        public static final int FRONT_LEFT_DRIVE_MOTOR_ID = 12;
        public static final int FRONT_LEFT_STEER_MOTOR_ID = 11;
        public static final int FRONT_LEFT_ENCODER_ID = 17;
        public static final Angle FRONT_LEFT_ENCODER_OFFSET = Rotations.of(-0.451416);
        public static final boolean FRONT_LEFT_STEER_MOTOR_INVERTED = false;
        public static final boolean FRONT_LEFT_ENCODER_INVERTED = false;

        public static final Distance FRONT_LEFT_X_POS = Inches.of(11.375);
        public static final Distance FRONT_LEFT_Y_POS = Inches.of(10.375);

        // Front Right
        public static final int FRONT_RIGHT_DRIVE_MOTOR_ID = 10;
        public static final int FRONT_RIGHT_STEER_MOTOR_ID = 9;
        public static final int FRONT_RIGHT_ENCODER_ID = 18;
        public static final Angle FRONT_RIGHT_ENCODER_OFFSET = Rotations.of(0.258789);
        public static final boolean FRONT_RIGHT_STEER_MOTOR_INVERTED = false;
        public static final boolean FRONT_RIGHT_ENCODER_INVERTED = false;

        public static final Distance FRONT_RIGHT_X_POS = Inches.of(11.375);
        public static final Distance FRONT_RIGHT_Y_POS = Inches.of(-10.375);

        // Back Left
        public static final int BACK_LEFT_DRIVE_MOTOR_ID = 4;
        public static final int BACK_LEFT_STEER_MOTOR_ID = 3;
        public static final int BACK_LEFT_ENCODER_ID = 14;
        public static final Angle BACK_LEFT_ENCODER_OFFSET = Rotations.of(0.186279);
        public static final boolean BACK_LEFT_STEER_MOTOR_INVERTED = false;
        public static final boolean BACK_LEFT_ENCODER_INVERTED = false;

        public static final Distance BACK_LEFT_X_POS = Inches.of(-11.375);
        public static final Distance BACK_LEFT_Y_POS = Inches.of(10.375);

        // Back Right
        public static final int BACK_RIGHT_DRIVE_MOTOR_ID = 8;
        public static final int BACK_RIGHT_STEER_MOTOR_ID = 7;
        public static final int BACK_RIGHT_ENCODER_ID = 16;
        public static final Angle BACK_RIGHT_ENCODER_OFFSET = Rotations.of(-0.129395);
        public static final boolean BACK_RIGHT_STEER_MOTOR_INVERTED = false;
        public static final boolean BACK_RIGHT_ENCODER_INVERTED = false;

        public static final Distance BACK_RIGHT_X_POS = Inches.of(-11.375);
        public static final Distance BACK_RIGHT_Y_POS = Inches.of(-10.375);

    }

    public class Intake
    {
        public static int LEFT_ID = 23;
        public static int RIGHT_ID = 33;

        public static final double STATOR_CURRENT_LIMIT = 60.0;
        public static final double SUPPLY_CURRENT_LIMIT = 40.0;

        public static final double INTAKE_VELOCITY = -30.0; // rot/s // not a bug
        public static final double REDUCED_INTAKE_VELOCITY = -20.0;
        public static final double DEFAULT_INTAKE_VELOCITY = 0.0;
        public static final double EJECT_VELOCITY = 25.0; // rot/s

        public static final double KP = 0.3;
		public static final double KI = 0.0;
		public static final double KD = 0.0;
		
        public static final double KS = 0.0;
        public static final double KV = 12.0/90.0; // max voltage/max speed = 12/(120/1.33)
        public static final double KA = 0.0;
        public static final InvertedValue LEFT_INVERTED = InvertedValue.CounterClockwise_Positive;
        public static final InvertedValue RIGHT_INVERTED = InvertedValue.CounterClockwise_Positive;

        
        public static final double LEFT_GEAR_RATIO = 16.0/12.0;
        public static final double RIGHT_GEAR_RATIO = 16.0/12.0;

        public static final double STALLING_CURRENT = 30.0;
        
        public static final ChassisReference MECHANICAL_ORIENTATION = ChassisReference.CounterClockwise_Positive;

    }

    public class IntakeExtension
    {
        public static int ID = 24;

        public static final double STATOR_CURRENT_LIMIT = 60.0;
        public static final double SUPPLY_CURRENT_LIMIT = 40.0;

        public static final double EXTENDING_VOLTAGE = 5.5;//5.0;
        public static final double RETRACTING_VOLTAGE = -3.5;
        public static final double HOLDING_EXTEND_VOLTAGE = 0.25;
        public static final double HOLDING_RETRACT_VOLTAGE = -0.25;

        public static final InvertedValue INVERTED = InvertedValue.CounterClockwise_Positive;
        
        public static final double GEAR_RATIO = 6.25;
        
        public static final ChassisReference MECHANICAL_ORIENTATION = ChassisReference.CounterClockwise_Positive;

        public static final double STALLING_CURRENT_EXTEND = 14.0; //15.0;//19;
        public static final double STALLING_CURRENT_RETRACT = 14.0; //16.5;//19; // might need to be lower

        public static final double MIN_HEIGHT = 0.0;
        public static final double MAX_HEIGHT = 1.0;
        
        public static final double STALLING_DEBOUNCE_TIME = 0.4; // 0.1

        public static final double AGITATE_MIN_VOLTAGE = -1.0; // TODO
        public static final double AGITATE_MAX_VOLTAGE = 1.0; // TODO
        public static final double AGITATE_PERIOD_SECONDS = 1.0; // TODO
    }

    public class Indexer 
    {
        public static final int MAIN_ID = 31;

        public static final InvertedValue MAIN_INVERTED = InvertedValue.CounterClockwise_Positive;
        public static final double MAIN_STATOR_CURRENT_LIMIT = 60.0; // amps
        public static final double MAIN_SUPPLY_CURRENT_LIMIT = 60.0; // amps

        public static final double MAIN_KS = 0.0048438;
        public static final double MAIN_KV = 0.12361;
        public static final double MAIN_KA = 0.0089587;
        
        public static final double MAIN_KP = 0.093687;
        public static final double MAIN_KI = 0.0;
        public static final double MAIN_KD = 0.0;

        
        /*
        public static final double MM_CRUISE_VELOCITY = 0.0;  
        public static final double MM_ACCELERATION = 0.0;
        public static final double MM_JERK = 0.0;
        */

        public static final double MAIN_MAX_VOLTAGE = 4.5;//3.5; // volts
        public static final double MAIN_DEFAULT_VOLTAGE = 0.0; // volts
        public static final double MAIN_EJECT_VOLTAGE = -3.5; // volts

        public static final double MAIN_GEAR_RATIO = 16.0/12.0;

        public static final ChassisReference MAIN_MECHANICAL_ORIENTATION = ChassisReference.Clockwise_Positive;
    }

    public class ShooterIndexer
    {
        public static final int ID = 32;

        public static final InvertedValue INVERTED = InvertedValue.CounterClockwise_Positive;
        public static final double STATOR_CURRENT_LIMIT = 60.0;
        public static final double SUPPLY_CURRENT_LIMIT = 40.0;

        public static final double DEFAULT_VOLTAGE = 0.0;
        public static final double INTAKE_VOLTAGE = 8.0;//6.0;

        public static final double INTAKE_VELOCITY = 25.0; // rot/s
        public static final double EJECT_VELOCITY = -25.0; // rot/s
        
        public static final double KS = 0;
        public static final double KV = 0;
        public static final double KA = 0;
        
        public static final double KP = 1.0;
        public static final double KI = 0.0;
        public static final double KD = 0.0;

        public static final double GEAR_RATIO = 3.0;

        public static final ChassisReference MECHANICAL_ORIENTATION = ChassisReference.CounterClockwise_Positive;
    }

    public class Hood
    {
        public static final int ID = 26;
        
        public static final double STATOR_CURRENT_LIMIT = 60.0;
        public static final double SUPPLY_CURRENT_LIMIT = 40.0;

		public static final InvertedValue INVERTED = InvertedValue.Clockwise_Positive;
        
        public static final double GEAR_RATIO = 136.67; // sensor to hood angle

		public static final double KP = 350.0;
		public static final double KI = 50.0;
		public static final double KD = 0.0;
		
        public static final double KS = 0.26106;//0.10056; //0.44797;
        public static final double KV = 0.63103;//0.010435;
        public static final double KA = 3.1495;//0.00053474;
		public static final double KG = 0.0; //0.06144;

        public static final ChassisReference MECHANICAL_ORIENTATION = ChassisReference.CounterClockwise_Positive;

        public static final double MAX_ERROR = 0.5;//0.25;
    
        public static final double STALLING_CURRENT = 10.0;

        public static final double MANUAL_UP_VOLTAGE = -0.5;
        public static final double MANUAL_DOWN_VOLTAGE = 0.5;
        
        public static final double ZEROING_VOLTAGE = 1.0;
        public static final double ZEROING_POSITION = 75.5; 
        // because the hood current zeroes too high up for some reason and we don't
        // want the hood to stall when it goes to 75 degrees (its max angle)

        public static final double DEBOUNCE_TIME = 0.1;
    }
    
    public class Shooter
    {
        public static final int MASTER_ID = 21;
        public static final int FOLLOWER_ID = 19;
        
        public static final double STATOR_CURRENT_LIMIT = 60.0;
        public static final double SUPPLY_CURRENT_LIMIT = 40.0;

		public static final InvertedValue INVERTED = InvertedValue.Clockwise_Positive;
        public static final MotorAlignmentValue MOTOR_ALIGNMENT = MotorAlignmentValue.Opposed;
        
        public static final double GEAR_RATIO = 20.0/12.0;

		public static final double KP = 0.7; // 0.1;
		public static final double KI = 0.0;
        public static final double KD = 0.0;
        public static final double KS = 0.14443; // 0.13:
        public static final double KV = 0.19085; // 0.19241;
        public static final double KA = 0.015006; // 0.013044;
		
        public static final double DEFAULT_VELOCITY = 0.0; // meters per second
        public static final double SOFT_PASS_VELOCITY = 6.5; // meters per second

        public static final ChassisReference MASTER_MECHANICAL_ORIENTATION = ChassisReference.CounterClockwise_Positive;
        public static final ChassisReference FOLLOWER_MECHANICAL_ORIENTATION = ChassisReference.CounterClockwise_Positive;

        public static final double FLYWHEEL_CIRCUMFERANCE = Inches.of(4.0).times(Math.PI).in(Meters); // radius of 2 inches
        
        public static final double MAX_ERROR = 0.2;
    }

    public static final class Climb 
    {
        public static final int CLIMBWHEELS_ID = 61;
        public static final int SPOOLING_ID = 62;

        public static final InvertedValue CLIMBWHEELS_INVERTED = InvertedValue.CounterClockwise_Positive;
        public static final InvertedValue SPOOLING_INVERTED = InvertedValue.CounterClockwise_Positive;

        public static final ChassisReference CLIMBWHEELS_MECHANICAL_ORIENTATION = ChassisReference.CounterClockwise_Positive;
        public static final ChassisReference SPOOLING_MECHANICAL_ORIENTATION = ChassisReference.CounterClockwise_Positive;

        public static final double CLIMBWHEELS_GEAR_RATIO = 27.0;
        public static final double SPOOLING_GEAR_RATIO = 60.0;

        public static final double KP_CLIMBWHEELS = 1.0; // TODO
        public static final double KP_SPOOLING = 1.0; // TODO
        public static final double KI_CLIMBWHEELS = 0.0; //TODO
        public static final double KI_SPOOLING = 0.0; // TODO
        public static final double KD_CLIMBWHEELS = 0.0; //TODO
        public static final double KD_SPOOLING = 0.037935; // TODO

        public static final double CLIMBWHEELS_STATOR_CURRENT_LIMIT = 90.0;
        public static final double CLIMBWHEELS_SUPPLY_CURRENT_LIMIT = 40.0;
        public static final double SPOOLING_STATOR_CURRENT_LIMIT = 90.0;
        public static final double SPOOLING_SUPPLY_CURRENT_LIMIT = 40.0;

        public static final double SPOOLING_STALLING_CURRENT = 20;
		
        public static final Angle MAX_ERROR = Rotations.of(0.1);

        // positive voltage on CLIMBWHEELS = driving CLIMBWHEELS up
        public static final Voltage CLIMB_DOWN_VOLTAGE = Volts.of(3.0); //TODO
        public static final Voltage CLIMB_UP_VOLTAGE =  Volts.of(-3.0); // TODO

        // positive voltage on climb = deploying climb
        public static final Voltage SPOOL_VOLTAGE = Volts.of(2.4); // TODO
        public static final Voltage UNSPOOL_VOLTAGE = Volts.of(-2.4); // TODO

        public static final double UNSPOOL_TIME = 2.0; // seconds


        

    }


    public class Simulation
    {
        public static final double FIELD_HEIGHT = 8.069326;//meters
        public static final double FIELD_WIDTH = 16.540988;//meters

        // excluding steel barrier
        public static final Rectangle2d DEPOT = new Rectangle2d(
            new Translation2d(0.0, FIELD_HEIGHT - 1.570736 - 0.0762),
            new Translation2d(0.6858 - 0.0762, FIELD_HEIGHT - 1.570736 - 1.0668 + 0.0762));
        
        public static final Translation2d FIELD_CENTER = new Translation2d(FIELD_WIDTH / 2.0, FIELD_HEIGHT / 2.0);

        public static final Function<Double, Double> ROTATE_X = (Double x) -> x + 2 * (FIELD_CENTER.getX() - x);
        public static final Function<Double, Double> ROTATE_Y = (Double y) -> y + 2 * (FIELD_CENTER.getY() - y);

        public static final Translation2d CENTER_UPPER_REFERENCE = new Translation2d(FIELD_CENTER.getX(), FIELD_CENTER.getY() + 0.0254);
        public static final Translation2d CENTER_LOWER_REFERENCE = new Translation2d(FIELD_CENTER.getX(), FIELD_CENTER.getY() - 0.0254);

        public static final double FUEL_DIAMETER = 0.15;//meters
        public static final double MIN_FUEL_MASS = 0.203;//kg
        public static final double MAX_FUEL_MASS = 0.227;//kg

        public static final int TOTAL_FUEL = 504;
        public static final int FUELS_TAKEN_BY_OTHER_ROBOTS = 0;

        public static final Rectangle2d HUB_CONTENTS = new Rectangle2d(new Pose2d(new Translation2d(4.574794, 4.059936), new Rotation2d()), 1.1938, 1.1938);

        public static final Rectangle2d OUTPOST = new Rectangle2d(
            new Translation2d(-0.84 - 0.5 * FUEL_DIAMETER, 0.331 - 0.5 * FUEL_DIAMETER), 
            new Translation2d(-0.0708 + 0.5 * FUEL_DIAMETER, 1.008 + 0.5 * FUEL_DIAMETER));

        public static final Translation3d OUTPOST_SPAWN_LOCATION_LOWER = new Translation3d(0.5 * FUEL_DIAMETER, 0.2655, 0.714);
        public static final Translation3d OUTPOST_SPAWN_LOCATION_UPPER = new Translation3d(0.5 * FUEL_DIAMETER, 1.0735, 0.714);

        public static final BallConstants BALL_CONSTANTS = new BallConstants(
            (MAX_FUEL_MASS + MIN_FUEL_MASS) / 2.0,
            FUEL_DIAMETER / 2.0, 1.2, 0.30, 1.2, 0.35, 9.81, 20);

        public static final double HUB_INTAKE_HEIGHT = 1.8288;//meters
    }

    public static final Transform3d ROBOT_TO_HOOD = new Transform3d(0.3, 0.0, 0.34, Rotation3d.kZero); // TODO

    public static final Translation3d PASS_LEFT_TARGET_POSITION = new Translation3d(2.010664, 2.010664, 0.0);
    public static final Translation3d PASS_RIGHT_TARGET_POSITION = new Translation3d(2.010664, Simulation.FIELD_HEIGHT - 2.010664, 0.0);
    
    public static final Angle HARDCODE_HOOD_PITCH = Degrees.of(72.0);
    public static final double HARDCODE_VELOCITY = 7.35;

    public static final double PITCH_OFFSET_UNIT = 5.0;
    public static final double FLYWHEEL_OFFSET_UNIT = 0.5;

    public static final double DISTANCE_SHOOTVELO_RATIO = 0.7400067;
    public static final LinearVelocity SPEED_OFFSET = MetersPerSecond.of(0.275);

    public static final double ACCELERATION_LIMIT = 3.0;

    public static final double MID_PASS_VELOCITY = 12.7;
    public static final double MID_PASS_ANGLE = 65.0;
    
    public static final double HARD_PASS_VELOCITY = 18.0;
    public static final double HARD_PASS_ANGLE = 60.0;

    public static final boolean LOG_SIMULATION = false;
    public static final boolean LOG_REAL = false;
    public static final boolean LOG_CTRE = false;

    public static final boolean DATA_COLLECTION_MODE = false;
}